version: '3.9'

services:
  database:
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: rootwordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    
    volumes:
      - db:/var/lib/mysql

volumes:
  db: