version: "3.1"
services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    links:
      - "database"

    depends_on: [database]

    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: rootwordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpressdb

    volumes:
      - wordpress:/var/www/html


  database:
    image: mysql:8.1
    restart: always
    ports:
      - "80:3306"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: rootwordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
