services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: WORDPRESS_DB_HOST
        value: ${services.mysql-service.address}
      - key: WORDPRESS_DB_USER
        value: rootwordpress
      - key: WORDPRESS_DB_PASSWORD
        value: wordpresspassword
      - key: WORDPRESS_DB_NAME
        value: wordpressdb
      - key: PORT 
        value: 80
      

  - type: web
    name: mysql-service
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.mysql
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
      - key: MYSQL_DATABASE
        value: wordpressdb
      - key: MYSQL_USER
        value: rootwordpress
      - key: MYSQL_PASSWORD
        value: wordpresspassword
      - key: PORT 
        value: 3306

