services:
  - type: web
    name: wordpress
    env: docker
    region: oregon
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: WORDPRESS_DB_HOST
        value: ${db.HOST}
      - key: WORDPRESS_DB_USER
        value: rootwordpress
      - key: WORDPRESS_DB_PASSWORD
        value: wordpresspassword
      - key: WORDPRESS_DB_NAME
        value: wordpressdb
      - key: PORT 
        value: 80

  - type: web
    name: dbmysql
    dockerfilePath: ./Dockerfile.mysql
    healthCheckPath: /
    region: oregon
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: wordpressdb
      - key: MYSQL_USER
        value: rootwordpress
      - key: MYSQL_PASSWORD
        value: wordpresspassword